services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - compnet

  gateway:
    platform: linux/amd64
    # uncomment below to build from source
    # build:
    #   context: .
    #   dockerfile: ./gateway/Dockerfile-gateway
    image: ghcr.io/biosimulators/bio-compose-server-gateway:0.0.11-dev
    # STABLE is 0.0.5-dev
    container_name: gateway
    networks:
      - compnet
    depends_on:
      - mongodb

  worker:
    platform: linux/amd64
    # uncomment below to build from source
    # build:
    #   context: .
    #   dockerfile: ./worker/Dockerfile-worker
    image: ghcr.io/biosimulators/bio-compose-server-worker:0.0.10-dev
    # STABLE is 0.0.2-dev
    container_name: worker
    networks:
      - compnet
    depends_on:
      - mongodb

networks:
  compnet:
    driver: bridge