FROM ghcr.io/biosimulators/bio-compose-server-base:0.0.1-dev

# redundant line to ensure latest gateway content; comment out if you don't want this
# RUN rm -rf /bio-compose-server/shared \
#     && rm -rf /bio-compose-server/gateway
# COPY ./shared /bio-compose-server/shared
# COPY ./worker /bio-compose-server/gateway

ENTRYPOINT ["/entrypoint.sh"]

CMD ["uvicorn", "gateway.main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]
