FROM ghcr.io/biosimulators/bio-compose-server-base:latest
# STABLE IS 0.0.2-dev

LABEL org.opencontainers.image.title="bio-compose-server-gateway" \
    org.opencontainers.image.description="Base Docker image for BioCompose REST API management, job processing, and datastorage with MongoDB, ensuring scalable and robust performance." \
    org.opencontainers.image.url="https://compose.biosimulators.org/" \
    org.opencontainers.image.source="https://github.com/biosimulators/bio-compose-server" \
    org.opencontainers.image.authors="Alexander Patrie <apatrie@uchc.edu>, BioSimulators Team <info@biosimulators.org>" \
    org.opencontainers.image.vendor="BioSimulators Team"

SHELL ["/usr/bin/env", "bash", "-c"]

# RUN conda run -n server poetry config virtualenvs.create false \
#     && conda run -n server poetry lock \
#     && conda run -n server poetry install

RUN conda run -n server bash -c "\
    poetry config virtualenvs.create false && \
    poetry lock && \
    poetry install"

# expose for gateway
EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]

CMD ["uvicorn", "gateway.main:app", "--port", "8000", "--host 0.0.0.0", "--reload"]
