openapi: 3.1.0
info:
  title: bio-compose-server
  version: 0.0.1
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /get-process-bigraph-addresses:
    get:
      tags:
      - Composition
      summary: Get process bigraph implementation addresses for composition specifications.
      operationId: get-process-bigraph-addresses
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BigraphRegistryAddresses'
  /submit-composition:
    post:
      tags:
      - Composition
      summary: Submit composition spec for simulation
      operationId: submit-composition
      parameters:
      - name: simulators
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
          description: Simulator package names to use for implementation
          title: Simulators
        description: Simulator package names to use for implementation
      - name: duration
        in: query
        required: true
        schema:
          type: integer
          description: Duration of simulation
          title: Duration
        description: Duration of simulation
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_submit-composition'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompositionRun'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /get-output/{job_id}:
    get:
      tags:
      - Results
      summary: Get the results of an existing simulation run.
      operationId: get-output
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputData'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /get-composition-state/{job_id}:
    get:
      tags:
      - Composition
      summary: Get the composite spec of a given simulation run indexed by job_id.
      operationId: get-composition-state
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BigraphRegistryAddresses:
      properties:
        version:
          type: string
          title: Version
        registered_addresses:
          items:
            type: string
          type: array
          title: Registered Addresses
      type: object
      required:
      - version
      - registered_addresses
      title: BigraphRegistryAddresses
    Body_submit-composition:
      properties:
        spec_file:
          type: string
          format: binary
          title: Spec File
          description: Composition JSON File
      type: object
      required:
      - spec_file
      title: Body_submit-composition
    CompositionRun:
      properties:
        job_id:
          type: string
          title: Job Id
        last_updated:
          type: string
          title: Last Updated
        simulators:
          items:
            type: string
          type: array
          title: Simulators
        duration:
          type: integer
          title: Duration
        spec:
          type: object
          title: Spec
        status:
          type: string
          title: Status
          default: PENDING
        results:
          type: object
          title: Results
      type: object
      required:
      - job_id
      - last_updated
      - simulators
      - duration
      - spec
      title: CompositionRun
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OutputData:
      properties:
        job_id:
          type: string
          title: Job Id
        status:
          type: string
          title: Status
        last_updated:
          type: string
          title: Last Updated
        results:
          type: object
          title: Results
      type: object
      required:
      - job_id
      - status
      - last_updated
      - results
      title: OutputData
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
