FROM ghcr.io/biosimulators/bio-compose-server-base:0.0.1

# redundant line to ensure latest worker content; comment out if you don't want this
COPY ./shared /bio-compose-server/shared
COPY ./worker /bio-compose-server/worker

ENTRYPOINT ["/usr/bin/env"]
# CMD ["source", "/.bashrc", "&&", "python3", "worker/main.py"]
CMD ["bash"]
