FROM ghcr.io/biosimulators/bio-compose-server-base:latest
# STABLE IS 0.0.2-dev

LABEL org.opencontainers.image.title="bio-compose-server-worker" \
    org.opencontainers.image.description="Base Docker image for BioCompose REST API management, job processing, and datastorage with MongoDB, ensuring scalable and robust performance." \
    org.opencontainers.image.url="https://compose.biosimulators.org/" \
    org.opencontainers.image.source="https://github.com/biosimulators/bio-compose-server" \
    org.opencontainers.image.authors="Alexander Patrie <apatrie@uchc.edu>, BioSimulators Team <info@biosimulators.org>" \
    org.opencontainers.image.vendor="BioSimulators Team"

SHELL ["/usr/bin/env", "bash", "-c"]

COPY ./gateway /bio-compose-server/gateway
COPY ./shared /bio-compose-server/shared
COPY ./worker /bio-compose-server/worker

RUN apt-get update \
    && apt-get install -y \
        meson \
        g++ \
        gfortran \
        libblas-dev \
        liblapack-dev \
        libgfortran5 \
        libhdf5-dev \
        libhdf5-serial-dev \
        libatlas-base-dev \
        cmake \
        make \
        git \
        build-essential \
        python3-dev \
        swig \
        libc6-dev \
        libx11-dev \
        libc6 \
        libgl1-mesa-dev \
        pkg-config \
        curl \
        tar \
        libgl1-mesa-glx \
        libice6 \
        libsm6 \
        gnupg \
        libstdc++6 \
        && apt-get clean

# RUN conda run -n server poetry config virtualenvs.create false \
#     && conda run -n server poetry lock \
#     && conda run -n server poetry install \
#     && conda install -n server conda-forge::pymem3dg -y

RUN conda run -n server bash -c "\
    poetry config virtualenvs.create false && \
    poetry lock && \
    poetry install" \
    && conda install -n server conda-forge::pymem3dg -y

ENTRYPOINT ["/entrypoint.sh"]

CMD ["python3", "worker/main.py"]

